# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

def shared_pods_for_target
    pod 'RxSwift'
    pod 'RxCocoa'
    pod 'Alamofire'
    pod 'ObjectMapper'
    pod 'Kingfisher'
end

target 'GoodDay' do
    use_frameworks!
    
    pod 'RxSwift'
    pod 'RxCocoa'
    pod 'Alamofire'
    pod 'ObjectMapper'
    pod 'Kingfisher'
    
    target 'GoodDayTests' do
        inherit! :search_paths
        shared_pods_for_target
    end
    
    target 'GoodDayUITests' do
        inherit! :search_paths
        shared_pods_for_target
    end
    
end
