# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

def shared_pods_for_target
    pod 'RxSwift'
    pod 'RxCocoa'
    pod 'Alamofire'
    pod 'ObjectMapper'
    pod 'Kingfisher'
    pod 'AFNetworking'
end

target 'GoodDay' do
    use_frameworks!
    shared_pods_for_target
    
    target 'GoodDayTests' do
        inherit! :search_paths
        
    end
    
    target 'GoodDayUITests' do
        inherit! :search_paths
    end
    
end
